### ISSUE TITLE
Insert, Update, Upsert do not respect Decompose attribute

### ISSUE THREAD

**Issue by agrinei** [TortugaResearch/Chain#192]
I've created the following FacebookUser class to represent user data coming from Facebook Graph API. When retrieving data from the database the datasource respects the Decompose attribute but it doesn't when inserting or updating. I'm using a SqlServerDataSource.

`

    public class FacebookUser
    {
        public class AgeRange
        {
            public int? min { get; set; }
            public int? max { get; set; }
        }

        public class Picture
        {
            [Decompose("data_")]
            public PictureData data { get; set; }
        }

        public class PictureData
        {
            public bool is_silhouette { get; set; }
            public string url { get; set; }
        }

        public long id { get; set; }
        public string name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }

        [Decompose("age_range_")]
        public AgeRange age_range { get; set; }
        public string link { get; set; }
        public string gender { get; set; }
        public string locale { get; set; }
        public string timezone { get; set; }
        public DateTime updated_time { get; set; }
        public bool verified { get; set; }
        public string email { get; set; }

        [Decompose("picture_")]
        public Picture picture { get; set; }
    }
`

**Comment by Grauenwolf** [comment]
That's by design. Usually it is used for joined tables that wouldn't have been updated anyways.

But since it is causing you problems, we can look into changing the design.

**Comment by agrinei** [comment]
Understood! Maybe the Decompose attribute could have additional parameters specifying if it should be considered for insert/update/upsert.

**Comment by Grauenwolf** [comment]
That's what I'm thinking. The parameter would need to have at least 3 options:

Read only
Read/Write, parent takes priority
Read/Write, child takes priority

Priority deals with the parent and child having the same property name.

**Comment by agrinei** [comment]
Sounds good. But if the user defines a prefix that would prevent name conflicts * in most cases *, I think.

**Comment by Grauenwolf** [comment]
Oh definitely. The prefix is assumed to be part of the column name.

-----Original Message-----

**Comment by Grauenwolf** [comment]
See also https://github.com/docevaad/Anchor/issues/9

**Comment by Grauenwolf** [comment]
This is probably never going to happen.
